### ISSUE TITLE
Typo in aeolus readme

### ISSUE THREAD

**Issue by stuppie** [ltscomputingllc/faersdbstats#1]
Not sure if this is the right place for this, but:
In the README.txt file in the AEOLUS data available here: http://datadryad.org/resource/doi:10.5061/dryad.8q0s4

On line 48 there is tab character in "ADD	INDEX idx_standard_case_indication_indication_concept_id"

On line 55: 
ALTER TABLE standard_unique_all_case INDEX idx_standard_unique_all_case_caseid (caseid(255)), ADD INDEX idx_standard_unique_all_case_primary_id (primaryid(255)), ADD INDEX idx_standard_unique_all_case_isr (isr(255));
 should be
ALTER TABLE standard_unique_all_case **ADD** INDEX idx_standard_unique_all_case_caseid (caseid(255)), ADD INDEX idx_standard_unique_all_case_primary_id (primaryid(255)), ADD INDEX idx_standard_unique_all_case_isr (isr(255));

Thanks!

**Comment by leeevans** [comment]
@stuppie Thanks for creating the issue.

@jmbanda do you have the ability to update the README.txt file in that repo?
