### ISSUE TITLE
SQL version in AEOLUS README.txt

### ISSUE THREAD

**Issue by rossdb** [ltscomputingllc/faersdbstats#2]
Apologies if this question is completely off-base. The paper by Banda et al. in _Scientific _Data__ mentions PostgreSQL 9.3 as the SQL version used for AEOLUS. However, the code in the README.txt file at  [](http://datadryad.org/resource/doi:10.5061/dryad.8q0s4 ) gives an error when I try to run it on a PostgreSQL server, and seems to use mySQL vocabulary and syntax (e.g., INT(11) in the CREATE TABLE statements and LOAD DATA INFILE in the statements used to populate the tables).

Should I switch to mySQL, or is the code on GitHub in PostgreSQL (or am I completely missing something else)? Thanks!

**Comment by leeevans** [comment]
The converted data is in a mySQL database.  
The database conversion was done in a PostgreSQL database using Postgres SQL.

If you just want to use the converted data, load it into a mySQL database. 
If you want to run the conversion yourself using the SQL code in this github repo then you will need to use a Postgres database.

**Comment by rossdb** [comment]
Got it - thanks!

David
