### ISSUE TITLE
Extract Original Drug Indications

### ISSUE THREAD

**Issue by stuppie** [ltscomputingllc/faersdbstats#3]
It seems that the "outcomes" of a particular drug include the "indications" that it was originally prescribed for. Is there a best-practices of removing the prescribed indications of a drug from the list of side-effects/outcomes for that drug?

For example, the top outcomes for the drug 'Imatinib' (drug_concept_id: 1304107) are: Death,  Nausea, Diarrhoea, Vomiting, Malignant neoplasm progression, Anaemia, Pyrexia, Fatigue, Dyspnoea, Neoplasm malignant, Rash, Oedema peripheral, Chronic myeloid leukaemia. 'Chronic myeloid leukaemia' is an indication for which the drug Imatinib is often used, however it is often listed as an outcome (case_count: 616 in 'standard_drug_outcome_statistics' table).

I've tried filtering this using the 'standard_case_indication' table. However, I get the opposite problem: outcomes often show up as indications. For example, the top indications for 'Imatinib' include Nausea (187 counts), Anxiety (186 counts), Vomiting (98 counts), which look like outcomes to me. 

I've included the SQL queries I'm using below. I'm hoping I'm simply querying the database wrong? Maybe I'm getting all symptoms/indications for which these patients were treated, not just indications specific for imatinib? Is there a way to get the drug's specific indications? Thanks in advance.

_Extracting outcomes for imatinib_
```
SELECT aeolus.standard_drug_outcome_statistics.*,
drug_concept.vocabulary_id AS 'drug_vocabulary',
drug_concept.concept_code AS 'drug_concept_code',
drug_concept.concept_name AS 'drug_name',
outcome_concept.vocabulary_id AS 'outcome_vocabulary',
outcome_concept.concept_code AS 'outcome_concept_code',
outcome_concept.concept_name AS 'outcome_name'
FROM aeolus.standard_drug_outcome_statistics
    LEFT JOIN concept AS drug_concept ON aeolus.standard_drug_outcome_statistics.drug_concept_id=aeolus.drug_concept.concept_id
    LEFT JOIN concept AS outcome_concept ON aeolus.standard_drug_outcome_statistics.outcome_concept_id=aeolus.outcome_concept.concept_id
WHERE drug_concept_id = 1304107
order by -case_count
LIMIT 10000;
```

_Extracting indications for imatinib_
```
SELECT indi_pt, count(indi_pt) FROM aeolus.standard_case_indication
 LEFT JOIN aeolus.standard_drug_outcome_drilldown ON aeolus.standard_drug_outcome_drilldown.primaryid=aeolus.standard_case_indication.primaryid
 LEFT JOIN aeolus.concept ON aeolus.standard_drug_outcome_drilldown.drug_concept_id=aeolus.concept.concept_id
WHERE drug_concept_id = 1304107
group by indi_pt;
```

https://github.com/SuLab/biothings.drugs/issues/6

**Comment by leeevans** [comment]
Hi @stuppie 

Each indication on the FAERS case should also be linked to the associated drug on the case using the indication table indi_drug_seq and the case drug table drug_seq columns. 

You may also want to limit the indications to those associated with the case primary suspect ('PS') drug and not include the indications associated with any secondary suspect drug or concomitant medications.

So your example for extracting indications for imatinib would look like this:

```
SELECT indi_pt, count(indi_pt) 
FROM aeolus.standard_case_indication  
LEFT JOIN aeolus.standard_case_drug ON aeolus.standard_case_drug.primaryid = aeolus.standard_case_indication.primaryid
AND aeolus.standard_case_indication.indi_drug_seq = aeolus.standard_case_drug.drug_seq 
LEFT JOIN aeolus.concept ON aeolus.standard_case_drug.standard_concept_id = aeolus.concept.concept_id 
WHERE aeolus.standard_case_drug.role_cod = ('PS')
AND aeolus.concept.concept_id = 1304107 
GROUP BY indi_pt
ORDER BY count(indi_pt) DESC;
```
 
Also consider applying a cut-off using either top N results with the order by count desc or filter where count > N. I ran the above SQL for a couple of other drugs and some of the FAERS indications that I saw with lower counts didn't look like accurate drug indications.
